"""FrankenUI Tasks Example"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../99_main.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'tasks', 'cards', 'dashboard', 'forms', 'music', 'auth', 'playground', 'mail', 'getting_started',
           'buttons', 'headings', 'themeswitcher', 'index']

# %% ../99_main.ipynb
from fasthtml.common import *
import fasthtml.common as fh
from fh_frankenui.components import *
from fh_frankenui.core import *
import re
from fasthtml.components import Uk_theme_switcher

# %% ../99_main.ipynb
app,rt = fast_app(hdrs=Theme.blue.headers(), pico=False)

# %% ../99_main.ipynb
from tasks import tasks_homepage
from cards import cards_homepage
from dashboard import dashboard_homepage
from forms import forms_homepage
from music import music_homepage
from auth import auth_homepage
from playground import playground_homepage
from mail import mail_homepage

# %% ../99_main.ipynb
@rt
def tasks():      return tasks_homepage
@rt
def cards():      return cards_homepage
@rt
def dashboard():  return dashboard_homepage
@rt 
def forms():      return forms_homepage
@rt
def music():      return music_homepage
@rt
def auth():       return auth_homepage
@rt
def playground(): return playground_homepage
@rt
def mail():       return mail_homepage

# %% ../99_main.ipynb
@rt
def getting_started():
    return render_md(open('GettingStarted.md').read())

# %% ../99_main.ipynb
from api_reference import docs_button, docs_heading

# %% ../99_main.ipynb
@rt
def buttons(): return Container(docs_button)
@rt
def headings(): return Container(docs_heading)

# %% ../99_main.ipynb
@rt
def themeswitcher(): return Div(Uk_theme_switcher(),cls="p-12")

# %% ../99_main.ipynb
@rt
def index():
    return Body(cls="bg-background text-foreground")(Div(cls="flex w-full")(
    NavContainer(
         Li(A("Getting Started", hx_get=getting_started, hx_target='#content')),
         NavParentLi(
             A("API Reference"),
             NavContainer(
                 Li(A('Buttons',hx_get=buttons, hx_target='#content')),
                 Li(A('Heading',hx_get=headings, hx_target='#content')),
                 parent=False
             )),
         NavParentLi(
            A('Examples'),
            NavContainer(
                Li(A('Tasks',     hx_get=tasks,      hx_target='#content')),
                Li(A('Cards',     hx_get=cards,      hx_target='#content')),
                Li(A('Dashboard', hx_get=dashboard,  hx_target='#content')),
                Li(A('Form',      hx_get=forms,      hx_target='#content')),
                Li(A('Music',     hx_get=music,      hx_target='#content')),
                Li(A('Auth',      hx_get=auth,       hx_target='#content')),
                Li(A('Playground',hx_get=playground, hx_target='#content')),
                Li(A('Mail',      hx_get=mail,       hx_target='#content')),
                parent=False)),
          Li(A("Theme",hx_get=themeswitcher, hx_target='#content')),

        uk_nav=True, cls=(NavT.primary,"space-y-4 p-4 w-1/7")),
    Div(getting_started(), id='content',cls='w-full')))

# %% ../99_main.ipynb
serve()
