"""FrankenUI Playground Example"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../07_playground.ipynb.

# %% auto 0
__all__ = ['preset_options', 'playground_homepage', 'playground_navbar', 'page']

# %% ../07_playground.ipynb
from fasthtml.common import *
import fasthtml.common as fh
from fh_frankenui import *
from fh_frankenui.core import *
from fh_frankenui.components import *

from fasthtml.svg import *


# %% ../07_playground.ipynb
preset_options = ["Grammatical Standard English", "Summarize for a 2nd grader",
        "Text to command","Q&A","English to other languages","Parse unstructured data",
        "Classification","Natural language to Python","Explain code","Chat","More examples"]

# %% ../07_playground.ipynb
def playground_navbar():
    save_modal = Modal(
        ModalTitle("Save preset"),
        P("This will save the current playground state as a preset which you can access later or share with others.",cls=("mt-1.5", TextFont.muted_sm)),
        LabelInput("Name",        id="name"), 
        LabelInput("Description", id="description"),
        ModalCloseButton("Save", cls=(ButtonT.primary)),
        id="save")
    
    share_dd = Div(cls="space-y-6 p-4")(
        H3("Share preset"),
        P("Anyone who has this link and an OpenAI account will be able to view this.", cls=TextFont.muted_sm),
        Div(Input(value="https://platform.openai.com/playground/p/7bbKYQvsVkNmVb8NGcdUOLae?model=text-davinci-003", readonly=True, cls="flex-1"),
            Button(UkIcon('copy'), cls=(ButtonT.primary, "uk-drop-close"))))

    rnav = Div(cls='flex items-center space-x-2')(
        Select(*Options(*preset_options), name='preset', optgroup_label="Examples",
                 placeholder='Load a preset', searchable=True, cls='h-9 w-[200px] lg:w-[300px]'),
        Button("Save",         cls=ButtonT.secondary, uk_toggle="#save"),save_modal,
        Button("View Code",    cls=ButtonT.secondary),
        Button("Share",        cls=ButtonT.secondary),DropDownNavContainer(share_dd),
        Button(UkIcon("more"), cls=ButtonT.secondary),DropDownNavContainer(
            Li(A("Content filter preferences")),
            NavDividerLi(),
            Li(A("Delete preset", cls="text-destructive"))))
    
    return NavBarContainer(
                NavBarLSide(NavBarNav(H4('Playground'))),
                NavBarRSide(NavBarNav(rnav)))

# %% ../07_playground.ipynb
def playground_navbar():
    save_modal = Modal(
        ModalTitle("Save preset"),
        P("This will save the current playground state as a preset which you can access later or share with others.",cls=("mt-1.5", TextFont.muted_sm)),
        LabelInput("Name",        id="name"), 
        LabelInput("Description", id="description"),
        ModalCloseButton("Save", cls=(ButtonT.primary)),
        id="save")
    
    share_dd = Div(cls="space-y-6 p-4")(
        H3("Share preset"),
        P("Anyone who has this link and an OpenAI account will be able to view this.", cls=TextFont.muted_sm),
        Div(Input(value="https://platform.openai.com/playground/p/7bbKYQvsVkNmVb8NGcdUOLae?model=text-davinci-003", readonly=True, cls="flex-1"),
            Button(UkIcon('copy'), cls=(ButtonT.primary, "uk-drop-close"))))

    rnav = NavBarNav(
        Li(Select(*Options(*preset_options), name='preset', optgroup_label="Examples",
                 placeholder='Load a preset', searchable=True, cls='h-9 w-[200px] lg:w-[300px]')),
        Li(Button("Save",         cls=ButtonT.secondary, uk_toggle="#save"),save_modal),
        Li(Button("View Code",    cls=ButtonT.secondary)),
        Li(Button("Share",        cls=ButtonT.secondary),DropDownNavContainer(share_dd)),
        Li(Button(UkIcon("more"), cls=ButtonT.secondary),DropDownNavContainer(
            Li(A("Content filter preferences")),
            NavDividerLi(),
            Li(A("Delete preset", cls="text-destructive")))))
    
    return NavBarContainer(
                NavBarLSide(NavBarNav(Li(H4('Playground')))),
                NavBarRSide(rnav),
                cls='mt-2')

# %% ../07_playground.ipynb
def page():
    navbar = playground_navbar()
    
    main_content = Div(
        Div(cls="flex-1")(Textarea(cls="uk-textarea h-full p-4", placeholder="Write a tagline for an ice cream shop",readonly=True),),
        Div(cls="w-[200px] flex-none"),
        cls="flex h-[700px] gap-x-6 px-8 py-6")
    
    bottom_buttons = Div(
        Button("Submit", cls=ButtonT.primary),
        Button(UkIcon(icon="history"), cls=ButtonT.secondary),
        cls="flex gap-x-2 px-8 py-6 pt-0")
    
    return Div(navbar, main_content, bottom_buttons)

# %% ../07_playground.ipynb
playground_homepage = page()
