"""FrankenUI Tasks Example"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../99_main.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'reference_fns', 'api_ref_rts', 'sidebar', 'tasks', 'cards', 'dashboard', 'forms', 'music', 'auth',
           'playground', 'mail', 'getting_started', 'fnname2title', 'themeswitcher', 'index']

# %% ../99_main.ipynb
from fasthtml.common import *
import fasthtml.common as fh
from fh_frankenui.components import *
from fh_frankenui.core import *
import re
from fasthtml.components import Uk_theme_switcher
from utils import hjs

# %% ../99_main.ipynb
app,rt = fast_app(pico=False, hdrs=(*Theme.blue.headers(),*hjs))

# %% ../99_main.ipynb
from tasks import tasks_homepage
from cards import cards_homepage
from dashboard import dashboard_homepage
from forms import forms_homepage
from music import music_homepage
from auth import auth_homepage
from playground import playground_homepage
from mail import mail_homepage

# %% ../99_main.ipynb
@rt
def tasks():      return tasks_homepage
@rt
def cards():      return cards_homepage
@rt
def dashboard():  return dashboard_homepage
@rt 
def forms():      return forms_homepage
@rt
def music():      return music_homepage
@rt
def auth():       return auth_homepage
@rt
def playground(): return playground_homepage
@rt
def mail():       return mail_homepage

# %% ../99_main.ipynb
@rt
def getting_started():
    return Container(render_md(open('GettingStarted.md').read()))

# %% ../99_main.ipynb
import api_reference

# %% ../99_main.ipynb
reference_fns = L([o for o in dir(api_reference) if o.startswith('docs_')])
reference_fns

# %% ../99_main.ipynb
def fnname2title(ref_fn_name): return ref_fn_name[5:].replace('_',' | ').title() 

# %% ../99_main.ipynb
api_ref_rts = [(f"/{o}", app.add_route(f"/{o}", getattr(api_reference, o))) for o in reference_fns]

# %% ../99_main.ipynb
@rt
def themeswitcher(): return Div(Uk_theme_switcher(),cls="p-12")

# %% ../99_main.ipynb
sidebar = NavContainer(
     Li(A("Getting Started", hx_get=getting_started, hx_target="#content", hx_push_url='true')),
     NavParentLi(
         A(FullySpacedDiv("API Reference")),
         NavContainer(
             *[Li(A(fnname2title(o), hx_get=f"/{o}", hx_target="#content", hx_push_url='true')) for o in reference_fns],
             parent=False),
         ),
     NavParentLi(
        A(FullySpacedDiv('Examples')),
        NavContainer(
            Li(A('Tasks',     hx_get=tasks, hx_target="#content", hx_push_url='true')),
            Li(A('Cards',     hx_get=cards, hx_target="#content", hx_push_url='true')),
            Li(A('Dashboard', hx_get=dashboard, hx_target="#content", hx_push_url='true')),
            Li(A('Form',      hx_get=forms, hx_target="#content", hx_push_url='true')),
            Li(A('Music',     hx_get=music, hx_target="#content", hx_push_url='true')),
            Li(A('Auth',      hx_get=auth, hx_target="#content", hx_push_url='true')),
            Li(A('Playground',hx_get=playground, hx_target="#content", hx_push_url='true')),
            Li(A('Mail',      hx_get=mail, hx_target="#content", hx_push_url='true')),
            parent=False),
         ),
      Li(A("Theme",hx_get=themeswitcher,hx_target="#content", hx_push_url='true')),

    uk_nav=False, cls=(NavT.primary,"space-y-4 p-4 w-1/5"))

# %% ../99_main.ipynb
@rt
def index():return Body(cls="bg-background text-foreground")(Div(sidebar,Div(getting_started(),id="content", cls='w-full'),cls="flex"))

# %% ../99_main.ipynb
serve()
