"""FrankenUI Tasks Example"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../99_main.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'reference_fns', 'api_ref_rts', 'sidebar', 'with_layout', 'tasks', 'cards', 'dashboard', 'forms', 'music',
           'auth', 'playground', 'mail', 'getting_started', 'fnname2title', 'themeswitcher', 'index']

# %% ../99_main.ipynb
from fasthtml.common import *
import fasthtml.common as fh
from fh_frankenui.components import *
from fh_frankenui.core import *
import re
from fasthtml.components import Uk_theme_switcher
from utils import hjs

# %% ../99_main.ipynb
app,rt = fast_app(pico=False, hdrs=(*Theme.blue.headers(),*hjs))

# %% ../99_main.ipynb
def with_layout(func):
    def wrapper():
        original_content = func()
        return Body(cls="bg-background text-foreground")(
            Div(cls="flex flex-col md:flex-row w-full")(
                Button(UkIcon("menu",50,50,cls='mt-4'), cls="md:hidden mb-4", uk_toggle="target: #mobile-sidebar"),
                Div(sidebar, id='mobile-sidebar', hidden=True),
                
                Div(cls="md:flex w-full")(
                    Div(sidebar, cls="hidden md:block w-1/5"),
                    Div(original_content, cls='md:w-4/5 w-full', id="mobile-sidebar")
                )
            ),
        )
    wrapper.__name__ = func.__name__
    return wrapper

# %% ../99_main.ipynb
from tasks import tasks_homepage
from cards import cards_homepage
from dashboard import dashboard_homepage
from forms import forms_homepage
from music import music_homepage
from auth import auth_homepage
from playground import playground_homepage
from mail import mail_homepage

# %% ../99_main.ipynb
@rt
@with_layout
def tasks():      return tasks_homepage
@rt
@with_layout
def cards():      return cards_homepage
@rt
@with_layout
def dashboard():  return dashboard_homepage
@rt 
@with_layout
def forms():      return forms_homepage
@rt
@with_layout
def music():      return music_homepage
@rt
@with_layout
def auth():       return auth_homepage
@rt
@with_layout
def playground(): return playground_homepage
@rt
@with_layout
def mail():       return mail_homepage

# %% ../99_main.ipynb
@rt
@with_layout
def getting_started():
    return Container(render_md(open('GettingStarted.md').read()))

# %% ../99_main.ipynb
import api_reference

# %% ../99_main.ipynb
reference_fns = L([o for o in dir(api_reference) if o.startswith('docs_')])

# %% ../99_main.ipynb
api_ref_rts = [(f"/{o}", rt(f"/{o}")(with_layout(getattr(api_reference, o)))) for o in reference_fns]

# %% ../99_main.ipynb
def fnname2title(ref_fn_name): return ref_fn_name[5:].replace('_',' | ').title() 

# %% ../99_main.ipynb
@rt
@with_layout
def themeswitcher(): return Div(Uk_theme_switcher(),cls="p-12")

# %% ../99_main.ipynb
sidebar = NavContainer(
     Li(A("Getting Started", href=getting_started)),
     NavParentLi(
         A(FullySpacedDiv("API Reference")),
         NavContainer(
             *[Li(A(fnname2title(o), href=f"/{o}")) for o in reference_fns],
             parent=False),
         ),
     NavParentLi(
        A(FullySpacedDiv('Examples')),
        NavContainer(
            Li(A('Tasks',     href=tasks)),
            Li(A('Cards',     href=cards)),
            Li(A('Dashboard', href=dashboard)),
            Li(A('Form',      href=forms)),
            Li(A('Music',     href=music)),
            Li(A('Auth',      href=auth)),
            Li(A('Playground',href=playground)),
            Li(A('Mail',      href=mail)),
            parent=False),
         ),
      Li(A("Theme",href=themeswitcher)),

    uk_nav=False, cls=(NavT.primary,"space-y-4 p-4 w-full md:w-full"))

# %% ../99_main.ipynb
@rt
def index():return getting_started()

# %% ../99_main.ipynb
serve()
