"""FrankenUI Dashboard Example"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../ex_nbs/03_dashboard.ipynb.

# %% auto 0
__all__ = ['rev', 'sub', 'sal', 'act', 'top_info_row', 'recent_sales', 'db_nav', 'team_dropdown', 'headers', 'hotkeys', 'user',
           'avatar', 'avatar_dropdown', 'top_nav', 'dashboard_homepage', 'InfoCard', 'AvatarItem', 'generate_chart',
           'NavTab', 'UkTab', 'UkNavBar', 'page']

# %% ../ex_nbs/03_dashboard.ipynb 2
from fasthtml.common import *
from fh_frankenui.components import *
from fasthtml.svg import *
from fh_matplotlib import matplotlib2fasthtml
import numpy as np
import matplotlib.pylab as plt

# %% ../ex_nbs/03_dashboard.ipynb 9
def InfoCard(title, value, change):
    return Card(
             Div(UkH3(value),
                P(change, cls=TextT.muted_sm)),
             header = UkH4(title),)

# %% ../ex_nbs/03_dashboard.ipynb 11
rev = InfoCard("Total Revenue", "$45,231.89", "+20.1% from last month")
sub = InfoCard("Subscriptions", "+2350", "+180.1% from last month")
sal = InfoCard("Sales", "+12,234", "+19% from last month")
act = InfoCard("Active Now", "+573", "+201 since last hour")

# %% ../ex_nbs/03_dashboard.ipynb 12
top_info_row = Grid(rev,sub,sal,act,cols=2, gap=4, cls='lg:grid-cols-4')

# %% ../ex_nbs/03_dashboard.ipynb 15
def AvatarItem(name, email, amount):
    return Div(cls="flex items-center")(
        DiceBearAvatar(name, 9,9),
        Div(cls="ml-4 space-y-1")(
            P(name, cls=TextT.medium_sm),
            P(email, cls=TextT.muted_sm)),
        Div(amount, cls="ml-auto font-medium"))

recent_sales = Card(
    Div(cls="space-y-8")(
        *[AvatarItem(n,e,d) for (n,e,d) in (
            ("Olivia Martin",   "olivia.martin@email.com",   "+$1,999.00"),
            ("Jackson Lee",     "jackson.lee@email.com",     "+$39.00"),
            ("Isabella Nguyen", "isabella.nguyen@email.com", "+$299.00"),
            ("William Kim",     "will@email.com",            "+$99.00"),
            ("Sofia Davis",     "sofia.davis@email.com",     "+$39.00"))]),
    header=Div(
        UkH3("Recent Sales"),
        P("You made 265 sales this month.", cls=TextT.muted_sm)))

# %% ../ex_nbs/03_dashboard.ipynb 16
@matplotlib2fasthtml
def generate_chart(num_points):
    plotdata = [np.random.exponential(1) for _ in range(num_points)]
    plt.plot(range(len(plotdata)), plotdata)

# %% ../ex_nbs/03_dashboard.ipynb 19
def NavTab(text, active=False):
    return Li(cls="uk-active" if active else " ")(
        A(text, href="#demo", uk_toggle=True))

def UkTab(*items):
    return Ul(cls="uk-tab-alt max-w-96")(
        *[NavTab(item) for i, item in enumerate(items)])

db_nav = UkTab("Overview", "Analytics", "Reports", "Notifications")
show(db_nav)

# %% ../ex_nbs/03_dashboard.ipynb 21
def UkNavBar(*items):
    return Ul(cls="uk-navbar-nav gap-x-4 lg:gap-x-6")(
        *[NavTab(item) for i, item in enumerate(items)])

team_dropdown = UkDropdownButton("Alicia Koch", options = ("Alicia Koch","Acme Inc","Monster Inc.","Create a Team"))

# %% ../ex_nbs/03_dashboard.ipynb 25
headers = UkNavbar(lnav=(
    UkNavbarDropdown(*map(lambda x: A(x,href='#'), ["Alicia Koch"]), label="header")
))
show(headers)

# %% ../ex_nbs/03_dashboard.ipynb 26
hotkeys = (('Profile','⇧⌘P'), ('Billing','⌘B'), ('Settings','⌘S'), ('New Team',''), ('Logout',''))
user = (Div(cls='flex flex-col space-y-1')(P('Alicia Koch'),P('alicia@example.com',cls=TextT.muted_sm)),)
avatar = DiceBearAvatar('Alicia Koch',8,8)
avatar_dropdown = UkDropdownButton(
    avatar,
    user+hotkeys)

show(avatar_dropdown)

# %% ../ex_nbs/03_dashboard.ipynb 27
top_nav = Div(cls="flex items-center justify-between w-full")(
    Div(cls="flex items-center gap-x-4 lg:gap-x-6")(
        team_dropdown,
        UkNavBar("Overview", "Customers", "Products", "Settings")),
    Div(cls="flex items-center gap-x-4")(
        Div(cls="w-64")(UkInput(placeholder='Search')),
        avatar_dropdown))

show(top_nav)

# %% ../ex_nbs/03_dashboard.ipynb 29
def page():
    return Div(cls="space-y-4")(
        top_nav,
        UkHSplit(),
        UkH2('Dashboard'),
        db_nav, 
        top_info_row,
        Grid(Card(generate_chart(10),cls='lg:col-span-4'),
            Card(recent_sales,cls='lg:col-span-3'),
            gap=4,cls='lg:grid-cols-7'))

# %% ../ex_nbs/03_dashboard.ipynb 31
dashboard_homepage = page()
