"""FrankenUI Forms Example"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../ex_nbs/04_forms.ipynb.

# %% auto 0
__all__ = ['sidebar_options', 'sidebar', 'forms_homepage', 'heading', 'UkNav', 'Sidebar', 'HelpText', 'profile_form',
           'account_form', 'appearance_form', 'UkRadio', 'UkToggleSwitch', 'notifications_form', 'UkCheckbox',
           'display_form', 'page']

# %% ../ex_nbs/04_forms.ipynb 2
from fasthtml.common import *
from fh_frankenui.components import *
from fasthtml.svg import *
from fh_matplotlib import matplotlib2fasthtml
import numpy as np
import matplotlib.pylab as plt

# %% ../ex_nbs/04_forms.ipynb 9
def heading():
    return Div(cls="space-y-5")(
            UkH2("Settings"),
            P("Manage your account settings and set e-mail preferences.", cls=TextT.muted_sm),
            UkHSplit())

# %% ../ex_nbs/04_forms.ipynb 12
def UkNav(*c, cls="", **kwargs):
    nav_items = [Li(o) for o in c]
    nav_items[0].cls = " uk-active" # probably shouldn't be hard coded
    return Ul(*nav_items, cls=f"uk-nav uk-nav-secondary {cls}", **kwargs)

def Sidebar(*c, **kwargs):
    return Aside(**kwargs)(
        UkNav(*c, uk_switcher="connect: #component-nav; animation: uk-animation-fade"))

sidebar_options = [Div(o) for o in ("Profile", "Account", "Appearance", "Notifications", "Display")]

sidebar = Sidebar(*sidebar_options)

# %% ../ex_nbs/04_forms.ipynb 15
def HelpText(c):return P(c,cls=TextT.muted_sm)

# %% ../ex_nbs/04_forms.ipynb 16
def profile_form():
    return Div(cls="space-y-6")(
        Div(UkH3("Profile"),
            P("This is how others will see you on the site.", cls=TextT.medium_sm)),
        UkHSplit(),
        Div(cls="space-y-2")(
            UkInput("Username",placeholder='sveltecult', id='username'),
            HelpText("This is your public display name. It can be your real name or a pseudonym. You can only change this once every 30 days.")),
        Div(cls="space-y-2")(
            Label("Email", for_="email", cls="uk-form-label"),
            UkSelect(Option("Select a verified email to display", value="", selected=True, disabled=True),
                     *map(Option,("m@example.com","m@yahoo.com","m@cloud.com")),  
                     id="email"),
            HelpText("You can manage verified email addresses in your email settings.")),
        Div(cls="space-y-2")(
            UkTextArea("Bio", id="bio", placeholder="Tell us a little bit about yourself"),
            HelpText("You can @mention other users and organizations to link to them."),
            Div("String must contain at least 4 character(s)", cls="text-destructive")),
        Div(cls="space-y-2")(
            Span("URLs", cls="uk-form-label"),
            HelpText("Add links to your website, blog, or social media profiles."),
            UkInput(value="https://www.franken-ui.dev"),
            UkInput(value="https://github.com/sveltecult/franken-ui"),
            UkButton("Add URL")),
        Div(UkButton("Update profile", cls=UkButtonT.primary)))

# %% ../ex_nbs/04_forms.ipynb 18
def account_form():
    return Div(cls="space-y-6")(
        Div(UkH3("Account"),
            P("Update your account settings. Set your preferred language and timezone.", cls=TextT.medium_sm)),
        UkHSplit(),
        Div(cls="space-y-2")(
            UkInput("Name", placeholder="Your name", id="name"),
            HelpText("This is the name that will be displayed on your profile and in emails.")),
        Div(cls="space-y-2")(
            UkInput("Date of Birth", type="date", placeholder="Pick a date", id="date_of_birth", cls="w-[240px]"),
            HelpText("Your date of birth is used to calculate your age.")),
        Div(cls="space-y-2")(
            UkSelect(Option("Select a language", value="", disabled=True),
                     Option("English", selected=True),
                     *map(Option, ("French", "German", "Spanish", "Portuguese")),
                     label='Language',
                     id="language"),
            HelpText("This is the language that will be used in the dashboard.")),
        Div(UkButton("Update profile", cls=UkButtonT.primary)))


# %% ../ex_nbs/04_forms.ipynb 20
def appearance_form():
    return Div(cls="space-y-6")(
        Div(UkH3("Appearance"),
            P("Customize the appearance of the app. Automatically switch between day and night themes.", cls=TextT.medium_sm)),
        UkHSplit(),
        Div(cls="space-y-2")(
            UkSelect(Option("Select a font family", value="", disabled=True),
                     Option("Inter"),
                     Option("Geist", selected=True),
                     Option("Open Sans"),
                     label='Font Family',
                     id="font_family"),
            HelpText("Set the font you want to use in the dashboard.")),
        Div(cls="space-y-2")(
            Span("Theme", cls="uk-form-label"),
            HelpText("Select the theme for the dashboard."),
            Grid(A(id="theme-toggle-light", cls="block cursor-pointer items-center rounded-md border-2 border-muted p-1 ring-ring")(
                    Div(cls="space-y-2 rounded-sm bg-[#ecedef] p-2")(
                        Div(cls="space-y-2 rounded-md bg-white p-2 shadow-sm")(
                            Div(cls="h-2 w-[80px] rounded-lg bg-[#ecedef]"),
                            Div(cls="h-2 w-[100px] rounded-lg bg-[#ecedef]")),
                        Div(cls="flex items-center space-x-2 rounded-md bg-white p-2 shadow-sm")(
                            Div(cls="h-4 w-4 rounded-full bg-[#ecedef]"),
                            Div(cls="h-2 w-[100px] rounded-lg bg-[#ecedef]")),
                        Div(cls="flex items-center space-x-2 rounded-md bg-white p-2 shadow-sm")(
                            Div(cls="h-4 w-4 rounded-full bg-[#ecedef]"),
                            Div(cls="h-2 w-[100px] rounded-lg bg-[#ecedef]")))),
                A(id="theme-toggle-dark", cls="block cursor-pointer items-center rounded-md border-2 border-muted bg-popover p-1 ring-ring")(
                    Div(cls="space-y-2 rounded-sm bg-slate-950 p-2")(
                        Div(cls="space-y-2 rounded-md bg-slate-800 p-2 shadow-sm")(
                            Div(cls="h-2 w-[80px] rounded-lg bg-slate-400"),
                            Div(cls="h-2 w-[100px] rounded-lg bg-slate-400")),
                        Div(cls="flex items-center space-x-2 rounded-md bg-slate-800 p-2 shadow-sm")(
                            Div(cls="h-4 w-4 rounded-full bg-slate-400"),
                            Div(cls="h-2 w-[100px] rounded-lg bg-slate-400")),
                        Div(cls="flex items-center space-x-2 rounded-md bg-slate-800 p-2 shadow-sm")(
                            Div(cls="h-4 w-4 rounded-full bg-slate-400"),
                            Div(cls="h-2 w-[100px] rounded-lg bg-slate-400")))),
            cols=2,gap=8,cls='max-w-md')),
        Div(UkButton("Update preferences", cls=UkButtonT.primary)))

# %% ../ex_nbs/04_forms.ipynb 22
def UkRadio(label, id, name, checked=False, **kwargs):
    return Label(cls="block text-sm")(
        Input(id=id, cls="uk-radio mr-2", name=name, type="radio", checked=checked, **kwargs),
        label
    )

def UkToggleSwitch(id, checked=False, disabled=False, **kwargs):
    return Input(cls="uk-toggle-switch uk-toggle-switch-primary", id=id, type="checkbox", checked=checked, disabled=disabled, **kwargs)

def notifications_form():
    return Div(cls="space-y-6")(
        Div(UkH3("Notifications"),
            P("Configure how you receive notifications.", cls=TextT.medium_sm)),
        UkHSplit(),
        Div(cls="space-y-2")(
            Span("Notify me about", cls="uk-form-label"),
            *[UkRadio(label, f"notification_{i}", "notification", checked=(label=="Nothing"))
              for i, label in enumerate(["All new messages", "Direct messages and mentions", "Nothing"])]),
        Div(
            UkH3("Email Notifications", cls="mb-4 text-lg font-medium"),
            Div(cls="space-y-4")(
                *[Div(cls="flex items-center justify-between rounded-lg border border-border p-4")(
                    Div(cls="space-y-0.5")(
                        Label(item['title'], cls="text-base font-medium", for_=f"email_notification_{i}"),
                        HelpText(item['description'])),
                    UkToggleSwitch(f"email_notification_{i}", checked=item['checked'], disabled=item['disabled'])
                ) for i, item in enumerate([
                    {"title": "Communication emails", "description": "Receive emails about your account activity.", "checked": False, "disabled": False},
                    {"title": "Marketing emails", "description": "Receive emails about new products, features, and more.", "checked": False, "disabled": False},
                    {"title": "Social emails", "description": "Receive emails for friend requests, follows, and more.", "checked": True, "disabled": False},
                    {"title": "Security emails", "description": "Receive emails about your account activity and security.", "checked": True, "disabled": True}
                ])])),
        Div(cls="flex gap-x-3")(
            Input(cls="uk-checkbox mt-1", id="notification_mobile", type="checkbox", checked=True),
            Div(cls="space-y-1")(
                Label("Use different settings for my mobile devices", cls="uk-form-label", for_="notification_mobile"),
                HelpText("You can manage your mobile notifications in the mobile settings page."))),
        Div(UkButton("Update notifications", cls=UkButtonT.primary)))

# %% ../ex_nbs/04_forms.ipynb 24
def UkCheckbox(label, id, checked=False, **kwargs):
    return Label(cls="block text-sm", for_=id)(
        Input(cls="uk-checkbox mr-2", id=id, type="checkbox", checked=checked, **kwargs),
        label)

def display_form():
    return Div(cls="space-y-6")(
        Div(UkH3("Display"),
            P("Turn items on or off to control what's displayed in the app.", cls=TextT.medium_sm)),
        UkHSplit(),
        Div(cls="space-y-2")(
            Div(cls="mb-4")(
                Span("Sidebar", cls="text-base font-medium"),
                HelpText("Select the items you want to display in the sidebar.")),
            *[UkCheckbox(label, f"display_{i}", checked=i in [0, 1, 2])
              for i, label in enumerate(["Recents", "Home", "Applications", "Desktop", "Downloads", "Documents"])]),
        Div(UkButton("Update display", cls=UkButtonT.primary)))

# %% ../ex_nbs/04_forms.ipynb 25
def page():
    return Div(cls="p-6 lg:p-10")(
        heading(),
        Div(cls="flex gap-x-12")(
            Div(cls="w-1/5")(sidebar),
            Div(cls="flex-1")(
                Ul(id="component-nav", cls="uk-switcher max-w-2xl")(
                    Li(cls="uk-active")(profile_form(),
                    Li()(account_form()),
                    Li()(appearance_form()),
                    Li()(notifications_form()),
                    Li()(display_form())
                    )))))

# %% ../ex_nbs/04_forms.ipynb 26
forms_homepage = page()
