# AUTOGENERATED! DO NOT EDIT! File to edit: ../ex_nbs/05_music.ipynb.

# %% auto 0
__all__ = ['music_dd_data', 'file_dd_data', 'edit_dd_data', 'view_dd_data', 'account_dd_data', 'music_headers', 'sidebar_data',
           'cover', 'default_svg', 'tabs_data', 'music_homepage', 'SpacedPP', 'SpacedPPs', 'SpacedTxtIcon',
           'LAlignedTxtIcon', 'UkNavbarDropdown', 'UkNavbar', 'create_sidebar_section', 'create_playlists_section',
           'left_sidebar', 'sidebar_section', 'SidebarItem', 'SidebarSection', 'FrankenSidebar', 'TabItem',
           'FrankenTabs', 'create_album_grid', 'music_content', 'podcast_content', 'page']

# %% ../ex_nbs/05_music.ipynb 1
from fasthtml.common import *
from fasthtml.components import Uk
from fh_frankenui.components import *
from fasthtml.components import Uk_icon
from fasthtml.svg import *
from fh_matplotlib import matplotlib2fasthtml
import numpy as np
from pathlib import Path
import matplotlib.pylab as plt

# %% ../ex_nbs/05_music.ipynb 7
def SpacedPP(left, right=None):
    return FullySpacedContainer(P(left),P(right) if right else '')

def SpacedPPs(*c):
    return [SpacedPP(*tuplify(o)) for o in c]

def SpacedTxtIcon(txt, icon, ratio, icon_right=True):
    c = (P(txt),UkIcon(icon,ratio))
    if not icon_right: c = reversed(c)
    return FullySpacedContainer(*c)  

def LAlignedTxtIcon(txt, icon, ratio, icon_right=True):
    # TODO: Test and make sure this works
    # TODO: How do you pass text with a color? Should txt be a string?  Or should you pass a P?  
    c = (P(txt),UkIcon(icon,ratio))
    if not icon_right: c = reversed(c)
    return Div(cls='space-x-6')(*c)

# %% ../ex_nbs/05_music.ipynb 8
#TODO: Apply the above functions in here to finish that
# .disabled {opacity: 0.5; pointer-events: none; cursor: default; text-decoration: none;}
music_dd_data = [*SpacedPPs("About Music",("Preferences", "⌘")), UkHSplit(),
                 *SpacedPPs(("Hide Music", "⌘H"),("Hide Others", "⇧⌘H"),("Quit Music", "⌘Q"))]

# disabled = Burn Playlist to Disc | Print
file_dd_data = [*SpacedPPs("New" ,("Open Stream URL", "⌘U"),("Close Window", "⌘W")), UkHSplit(),
                *SpacedPPs("Library",("Import", "⌘O"),("Burn Playlist to Disc", )), UkHSplit(),
                *SpacedPPs(("Show in Finder", "⇧⌘R"),"Convert"), UkHSplit(),
                *SpacedPPs("Page Setup","Print")]

# disabled = Undo, Redo, Cut, Copy, Paste, Deselect All
edit_dd_data = [*SpacedPPs(("Undo", "⌘Z"),("Redo", "⇧⌘Z")), UkHSplit(), *SpacedPPs(("Cut", "⌘X"),("Copy", "⌘C"),("Paste", "⌘V")),
                UkHSplit(), *SpacedPPs(("Select All", "⌘A"),("Deselect All", "⇧⌘A")), UkHSplit(),
                SpacedTxtIcon('Smart Dictation','microphone',0.5), SpacedTxtIcon("Emojis & Symbols",'world',0.5)]

#disabled = Show Status Bar | Enter Full Screen
view_dd_data = SpacedPPs("Show Playing Next", "Show Lyrics", "Show Status Bar", "Hide Sidebar", "Enter Full Screen")

# header: Switch account
account_dd_data = [*SpacedPPs("Switch Account"),UkHSplit(),*SpacedPPs("Andy"), SpacedTxtIcon("Benoit", 'plus-circle',0.5),*SpacedPPs("Luis"),UkHSplit(),
                   *SpacedPPs("Manage Family"),UkHSplit(),*SpacedPPs("Add Account")]

# %% ../ex_nbs/05_music.ipynb 9
def UkNavbarDropdown(*c,label):
    return Li(A(label,href='#'),
        Div(cls='uk-navbar-dropdown')(
            Ul(cls='uk-nav uk-navbar-dropdown-nav')(*map(Li,c))))

# %% ../ex_nbs/05_music.ipynb 10
def UkNavbar(*c, cls=''):
    res = Div(cls='uk-navbar container '+ cls, uk_navbar=True)(
        Div(cls='uk-navbar-left')(
            Ul(cls='uk-navbar-nav')(*c)))
    return res

# %% ../ex_nbs/05_music.ipynb 11
music_headers = UkNavbar(
      UkNavbarDropdown(*map(lambda x: A(x,href='#'),music_dd_data),label='Music'),
      UkNavbarDropdown(*map(lambda x: A(x,href='#'),file_dd_data),label='File'),
      UkNavbarDropdown(*map(lambda x: A(x,href='#'),edit_dd_data),label='Edit'),
      UkNavbarDropdown(*map(lambda x: A(x,href='#'),view_dd_data),label='View'),
      UkNavbarDropdown(*map(lambda x: A(x,href='#'),account_dd_data),label='Account'))

# %% ../ex_nbs/05_music.ipynb 15
def create_sidebar_section(title, items):
    return Div(cls="px-3 py-2")(
        H2(title, cls="mb-2 px-3 text-lg font-semibold tracking-tight"),
        Ul(cls="uk-nav uk-nav-secondary")(
            *[Li(cls="uk-active" if i == 0 and title == "Discover" else None)(
                A(cls="font-medium", href="#demo", uk_toggle=True)(
                    Span(cls="mr-2 size-4")(Span(uk_icon=f"icon: {item['icon']}; ratio: 0.8")),
                    item['text']
                )
            ) for i, item in enumerate(items)]
        )
    )

def create_playlists_section(title, items):
    return Div(cls="px-3 py-2")(
        H2(title, cls="mb-2 px-3 text-lg font-semibold tracking-tight"),
        Div(cls="max-h-60 overflow-y-auto")(
            Ul(cls="uk-nav uk-nav-secondary")(
                *[Li(
                    A(cls="font-medium", href="#demo", uk_toggle=True)(
                        Span(cls="mr-2 size-4")(Span(uk_icon="icon: play; ratio: 0.9")),
                        item
                    )
                ) for item in items]
            )
        )
    )

def left_sidebar():
    discover_items = [
        {"text": "Listen Now", "icon": "play-circle"},
        {"text": "Browse", "icon": "thumbnails"},
        {"text": "Radio", "icon": "rss"},
    ]
    
    library_items = [
        {"text": "Playlists", "icon": "play-circle"},
        {"text": "Songs", "icon": "bell"},
        {"text": "Made for You", "icon": "user"},
        {"text": "Artists", "icon": "users"},
        {"text": "Albums", "icon": "bookmark"}
    ]
    
    playlist_items = [
        "Recently Added", "Recently Played", "Top Songs",
        "Top Albums", "Top Artists", "Logic Discography",
        "Bedtime Beats", "I miss Y2K Pop"
    ]
    
    return Div(cls="space-y-4 py-4 lg:block")(
        create_sidebar_section("Discover", discover_items),
        create_sidebar_section("Library", library_items),
        create_playlists_section("Playlists", playlist_items)
    )

# %% ../ex_nbs/05_music.ipynb 17
def sidebar_section(title, items, max_num_pre_scroll=6):
    content = Ul(cls="uk-nav uk-nav-secondary")(
        *[Li(cls="uk-active" if i == 0 and title == "Discover" else None)(
            A(cls="font-medium", href="#demo", uk_toggle=True)(
                Span(cls="mr-2 size-4")(Span(uk_icon=f"icon: {item['icon'] if isinstance(item, dict) else 'play'}; ratio: 0.8")),
                item['text'] if isinstance(item, dict) else item
            )
        ) for i, item in enumerate(items)]
    )
    
    if max_num_pre_scroll and len(items) > max_num_pre_scroll:
        content = Div(cls="max-h-60 overflow-y-auto")(content)
    
    return Div(cls="px-3 py-2")(
        H2(title, cls="mb-2 px-3 text-lg font-semibold tracking-tight"),
        content
    )

def left_sidebar():
    discover_items = [
        {"text": "Listen Now", "icon": "play-circle"},
        {"text": "Browse", "icon": "thumbnails"},
        {"text": "Radio", "icon": "rss"},
    ]
    
    library_items = [
        {"text": "Playlists", "icon": "play-circle"},
        {"text": "Songs", "icon": "bell"},
        {"text": "Made for You", "icon": "user"},
        {"text": "Artists", "icon": "users"},
        {"text": "Albums", "icon": "bookmark"}
    ]
    
    playlist_items = [
        "Recently Added", "Recently Played", "Top Songs",
        "Top Albums", "Top Artists", "Logic Discography",
        "Bedtime Beats", "I miss Y2K Pop"
    ]
    
    return Div(cls="space-y-4 py-4 lg:block")(
        sidebar_section("Discover", discover_items),
        sidebar_section("Library", library_items),
        sidebar_section("Playlists", playlist_items, max_num_pre_scroll=5)
    )

# %% ../ex_nbs/05_music.ipynb 19
from dataclasses import dataclass
from typing import List, Union, Optional

@dataclass
class SidebarItem:
    text: str
    icon: Optional[str] = None

@dataclass
class SidebarSection:
    title: str
    items: List[SidebarItem]
    max_num_pre_scroll: Optional[int] = None


class FrankenSidebar:
    """
    A class to create a sidebar with multiple sections.

    Attributes:
        sections (List[SidebarSection]): List of sidebar sections.

    Methods:
        add_section: Adds a new section to the sidebar.
        build: Builds the HTML for the entire sidebar.
        from_json: Creates a FrankenSidebar instance from a JSON-like structure.
    """

    def __init__(self):
        self.sections = []

    def add_section(self, title: str, items: List[Union[str, dict]], max_num_pre_scroll: Optional[int] = None):
        """
        Adds a new section to the sidebar.

        Args:
            title (str): The title of the section.
            items (List[Union[str, dict]]): List of items in the section. Each item can be a string or a dict with 'text' and 'icon' keys.
            max_num_pre_scroll (Optional[int]): Maximum number of items to show before adding a scroll. If None, all items are shown.
        """
        sidebar_items = [SidebarItem(item['text'], item['icon']) if isinstance(item, dict) else SidebarItem(item) for item in items]
        self.sections.append(SidebarSection(title, sidebar_items, max_num_pre_scroll))

    def build(self):
        """
        Builds the HTML for the entire sidebar.

        Returns:
            FT: The FastHTML object representing the sidebar.
        """
        def build_section(section):
            content = Ul(cls="uk-nav uk-nav-secondary")(
                *[Li(cls="uk-active" if i == 0 and section.title == "Discover" else None)(
                    A(cls="font-medium", href="#demo", uk_toggle=True)(
                        Span(cls="mr-2 size-4")(Span(uk_icon=f"icon: {item.icon or 'play'}; ratio: 0.8")),
                        item.text
                    )
                ) for i, item in enumerate(section.items)]
            )
            
            if section.max_num_pre_scroll and len(section.items) > section.max_num_pre_scroll:
                content = Div(cls="max-h-60 overflow-y-auto")(content)
            
            return Div(cls="px-3 py-2")(
                H2(section.title, cls="mb-2 px-3 text-lg font-semibold tracking-tight"),
                content
            )

        return Div(cls="space-y-4 py-4 lg:block")(
            *[build_section(section) for section in self.sections]
        )

    @classmethod
    def from_json(cls, json_data: List[dict]):
        """
        Creates a FrankenSidebar instance from a JSON-like structure.

        Args:
            json_data (List[dict]): A list of dictionaries, each representing a sidebar section.
                Each dictionary should have 'title', 'items', and optionally 'max_num_pre_scroll' keys.

        Returns:
            FrankenSidebar: An instance of FrankenSidebar with the sections from the JSON data.
        """
        sidebar = cls()
        for section in json_data:
            sidebar.add_section(section['title'], section['items'], section.get('max_num_pre_scroll'))
        return sidebar.build()

# %% ../ex_nbs/05_music.ipynb 20
sidebar_data = [
    {
        'title': 'Discover',
        'items': [
            {"text": "Listen Now", "icon": "play-circle"},
            {"text": "Browse", "icon": "thumbnails"},
            {"text": "Radio", "icon": "rss"},
        ]
    },
    {
        'title': 'Library',
        'items': [
            {"text": "Playlists", "icon": "play-circle"},
            {"text": "Songs", "icon": "bell"},
            {"text": "Made for You", "icon": "user"},
            {"text": "Artists", "icon": "users"},
            {"text": "Albums", "icon": "bookmark"}
        ]
    },
    {
        'title': 'Playlists',
        'items': [
            "Recently Added", "Recently Played", "Top Songs",
            "Top Albums", "Top Artists", "Logic Discography",
            "Bedtime Beats", "I miss Y2K Pop"
        ],
        'max_num_pre_scroll': 5
    }
]


# %% ../ex_nbs/05_music.ipynb 22
from dataclasses import dataclass, field
from typing import List, Optional, Union

@dataclass
class TabItem:
    text: str
    href: str = "#"
    active: bool = False
    disabled: bool = False
    tab_body: Union[str, FT] = field(default_factory=lambda: P("Placeholder content"))

class FrankenTabs:
    """
    A class to create a flexible and modular tab component with associated content.

    Attributes:
        items (List[TabItem]): List of tab items.
        connect_id (str): ID of the content to be connected with the tabs.
        animation (str): Animation type for tab switching.

    Methods:
        add_tab: Adds a new tab to the component.
        build: Builds the HTML for the entire tab component including content.
        from_json: Creates a FrankenTabs instance from a JSON-like structure.
    """

    def __init__(self, connect_id: str = "component-nav", animation: str = "uk-animation-fade"):
        self.items = []
        self.connect_id = connect_id
        self.animation = animation

    def add_tab(self, text: str, href: str = "#", active: bool = False, disabled: bool = False, tab_body: Union[str, FT] = None):
        """
        Adds a new tab to the component.

        Args:
            text (str): The text to display on the tab.
            href (str): The href attribute for the tab link.
            active (bool): Whether the tab should be active by default.
            disabled (bool): Whether the tab should be disabled.
            tab_body (Union[str, FT]): The content for the tab body.
        """
        self.items.append(TabItem(text, href, active, disabled, tab_body or P(f"Content for {text}")))

    def build(self):
        """
        Builds the HTML for the entire tab component including content.

        Returns:
            FT: The FastHTML object representing the tab component and its content.
        """
        def get_cls(item):
            cls = ("uk-active" if item.active else "") + (" uk-disabled" if item.disabled else "")
            return cls if len(cls) > 0 else None
        
        tabs = Ul(cls="uk-tab-alt", uk_switcher=f"connect: #{self.connect_id}; animation: {self.animation}")(
            *[Li(cls=get_cls(item))(
                A(item.text, href=item.href, cls="opacity-50" if item.disabled else None)
            ) for item in self.items]
        )

        content = Ul(id=self.connect_id, cls="uk-switcher mt-6")(
            *[Li(Div(cls="space-y-1")(item.tab_body)) for item in self.items]
        )

        return tabs, content

    @classmethod
    def from_json(cls, json_data: List[dict], connect_id: str = "component-nav", animation: str = "uk-animation-fade"):
        """
        Creates a FrankenTabs instance from a JSON-like structure.

        Args:
            json_data (List[dict]): A list of dictionaries, each representing a tab item.
                Each dictionary should have 'text', and optionally 'href', 'active', 'disabled', and 'tab_body' keys.
            connect_id (str): ID of the content to be connected with the tabs.
            animation (str): Animation type for tab switching.

        Returns:
            FrankenTabs: An instance of FrankenTabs with the tabs and content from the JSON data.
        """
        tabs = cls(connect_id, animation)
        for item in json_data:
            tabs.add_tab(
                text=item['text'],
                href=item.get('href', '#'),
                active=item.get('active', False),
                disabled=item.get('disabled', False),
                tab_body=item.get('tab_body')
            )
        return tabs.build()

# %% ../ex_nbs/05_music.ipynb 24
cover = os.path.expanduser("~/fh-frankenui-examples/images/album.svg")

default_svg = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMDAgMzAwIj4KICA8cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjMwMCIgZmlsbD0iI2UwZTBlMCIvPgogIDxjaXJjbGUgY3g9IjE1MCIgY3k9IjE1MCIgcj0iMTAwIiBmaWxsPSIjZmZmZmZmIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iOCIvPgogIDxjaXJjbGUgY3g9IjE1MCIgY3k9IjE1MCIgcj0iMzUiIGZpbGw9IiMwMDAwMDAiLz4KICA8cGF0aCBkPSJNMTUwIDMwIEwxNTAgMjcwIE0zMCAxNTAgTDI3MCAxNTAiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSI0Ii8+CiAgPHRleHQgeD0iMTUwIiB5PSIyOTAiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIyNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzAwMDAwMCI+QUxCVU08L3RleHQ+Cjwvc3ZnPg=="


def create_album_grid(albums, cols=4):
    return Div(cls=f"grid grid-cols-{cols} gap-x-4")(
        *[Div(cls="space-y-3")(
            Div(cls="overflow-hidden rounded-md")(
                Img(cls="transition-transform duration-200 hover:scale-105", src=album.get('cover', default_svg), alt="")
            ),
            Div(cls="space-y-1 text-sm")(
                H3(album['title'], cls="font-medium leading-none"),
                P(album['artist'], cls="text-xs text-muted-foreground")
            )
        ) for album in albums]
    )

def music_content():
    listen_now_albums = [
        {"title": "Roar", "artist": "Catty Perry"},
        {"title": "Feline on a Prayer", "artist": "Cat Jovi"},
        {"title": "Fur Elise", "artist": "Ludwig van Beethovpurr"},
        {"title": "Purrple Rain", "artist": "Prince's Cat"},
    ]
    
    made_for_you_albums = [
        {"title": "Like a Feline", "artist": "Catdonna"},
        {"title": "Livin' La Vida Purrda", "artist": "Ricky Catin"},
        {"title": "Meow Meow Rocket", "artist": "Elton Cat"},
        {"title": "Rolling in the Purr", "artist": "Catdelle",},
        {"title": "Purrs of Silence", "artist": "Cat Garfunkel"},
        {"title": "Meow Me Maybe", "artist": "Carly Rae Purrsen"},
    ]
    
    return Div(
        Div(cls="space-y-1")(
            H2("Listen Now", cls="text-2xl font-semibold tracking-tight"),
            P("Top picks for you. Updated daily.", cls="text-sm text-muted-foreground")
        ),
        Div(cls="my-4 h-[1px] w-full bg-border"),
        create_album_grid(listen_now_albums, cols=4),
        Div(cls="mt-6 space-y-1")(
            H2("Made for You", cls="text-2xl font-semibold tracking-tight"),
            P("Your personal playlists. Updated daily.", cls="text-sm text-muted-foreground")
        ),
        Div(cls="my-4 h-[1px] w-full bg-border"),
        create_album_grid(made_for_you_albums, cols=6)
    )


# %% ../ex_nbs/05_music.ipynb 26
def podcast_content():
    return Div(
        Div(cls="space-y-1")(
            H2("New Episodes", cls="text-2xl font-semibold tracking-tight"),
            P("Your favorite podcasts. Updated daily.", cls="text-sm text-muted-foreground")
        ),
        Div(cls="my-4 h-[1px] w-full bg-border"),
        Div(cls="uk-placeholder flex h-[450px] items-center justify-center rounded-md")(
            Div(cls="mx-auto flex max-w-[420px] flex-col items-center justify-center text-center")(
                Span(uk_icon="icon: podcast; ratio: 2"),
                H3("No episodes added", cls="mt-4 text-lg font-semibold"),
                P("You have not added any podcasts. Add one below.", cls="mb-4 mt-2 text-sm text-muted-foreground"),
                UkButton("Add Podcast", cls=UkButtonT.primary, uk_toggle="#demo")
            )
        )
    )

# %% ../ex_nbs/05_music.ipynb 27
tabs_data = [
    {"text": "Music", "active": True, "tab_body": music_content()},
    {"text": "Podcasts", "tab_body": podcast_content()},
    {"text": "Live", "disabled": True, "tab_body": P("Live content")}
]

# %% ../ex_nbs/05_music.ipynb 28
def page():
    tabs, content = FrankenTabs.from_json(tabs_data)
    return Div(
        music_headers,
        Div(cls="grid grid-cols-5")(
            Div(cls="hidden space-y-4 py-4 lg:block")(
                FrankenSidebar.from_json(sidebar_data)
            ),
            Div(cls="col-span-5 border-l border-border lg:col-span-4")(
                Div(cls="px-8 py-6")(
                    Div(cls="flex items-center justify-between")(
                        Div(cls="max-w-80")(tabs),
                        Div(
                            UkButton(cls=UkButtonT.primary)(
                                Span(cls="mr-2 size-4")(
                                    Span(uk_icon="icon: plus-circle; ratio: 0.8")
                                ),
                                "Add music"
                            )
                        )
                    ),
                    content
                )
            )
        )
    )

# %% ../ex_nbs/05_music.ipynb 29
music_homepage = page()
