# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh-frankenui',
                'doc_host': 'https://Isaac-Flath.github.io',
                'git_url': 'https://github.com/Isaac-Flath/fh-frankenui',
                'lib_path': 'fh_frankenui'},
  'syms': {'fh_frankenui.core': {'fh_frankenui.core.foo': ('core.html#foo', 'fh_frankenui/core.py')}}}
