# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_foundations.ipynb.

# %% auto 0
__all__ = ['BaseEnum', 'CoreEnum']

# %% ../nbs/00_foundations.ipynb 2
from fasthtml.common import *
from enum import Enum, EnumMeta, EnumType
import string

# %% ../nbs/00_foundations.ipynb 6
class BaseEnum(Enum):
    def __add__(self, other):
        return self.__str__() + other.__str__()
    
    def __str__(self):
        base = self.__class__.__name__       
        if isinstance(self.__class__, EnumType):
            base = base.rstrip(string.ascii_uppercase).rstrip('_')
        return f"uk-{base.lower()}-{self.value}".strip('-')


# %% ../nbs/00_foundations.ipynb 9
class CoreEnum(BaseEnum):
    def __init__(self, name):
        if isinstance(name, str): pass
        else:
            for enm in name:
                self.__setattr__(enm.name, enm)
