# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_style.ipynb.

# %% auto 0
__all__ = ['UkTyp']

# %% ../nbs/02_style.ipynb 2
from fasthtml.common import *
from .components import *
from enum import Enum

# %% ../nbs/02_style.ipynb 6
class UkTyp(Enum):
    default = 'default'
    ghost = 'ghost'
    primary = 'primary'
    secondary = 'secondary'
    danger = 'danger'

    def __str__(self): return self.value
